apiVersion: v1
kind: ConfigMap
metadata:
  name: expensepilot-backend-config
  namespace: expensepilot
data:
  APP_NAME: "ExpensePilot Capstone"
  ENVIRONMENT: "production"
  DB_HOST: "expensepilot-postgres"
  DB_PORT: "5432"
  DB_NAME: "expensepilot"
