apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expensepilot-postgres-pvc
  namespace: expensepilot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
