apiVersion: v1
kind: Service
metadata:
  name: taskboard-backend
  namespace: taskboard
  labels:
    app: taskboard-backend
spec:
  type: ClusterIP
  selector:
    app: taskboard-backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http
