frontend:
  image: ghcr.io/akshat-code21/expensepilot-frontend
  tag: k8s-backend-fix
backend:
  image: ghcr.io/akshat-code21/expensepilot-backend
  tag: latest
replicaCount: 2
namespace: expensepilot
imagePullSecrets: []
postgres:
  host: expensepilot-postgres
  database: expensepilot
  username: expensepilot
  password: expensepilot
ingress:
  enabled: true
  host: expensepilot.local
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
resources:
  requests: {cpu: 100m, memory: 256Mi}
  limits: {cpu: 500m, memory: 512Mi}
monitoring:
  serviceMonitor:
    enabled: false

