frontend:
  image: ghcr.io/akshat-code21/expensepilot-frontend
backend:
  image: ghcr.io/akshat-code21/expensepilot-backend
replicaCount: 2
ingress:
  enabled: true
  host: expensepilot.local
hpa:
  enabled: true

