apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: expensepilot-project
  namespace: argocd
spec:
  description: "GitOps project for ExpensePilot Application"
  sourceRepos:
    - "*"
  destinations:
    - namespace: expensepilot
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
