apiVersion: apps/v1
kind: Deployment
metadata:
  name: scenario3-backend-app
  namespace: expensepilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensepilot-backend-actual
  template:
    metadata:
      labels:
        app: expensepilot-backend-actual
    spec:
      containers:
        - name: app
          image: hashicorp/http-echo:latest
          args: ["-text=hello-from-backend", "-listen=:8080"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: scenario3-broken-service
  namespace: expensepilot
spec:
  type: ClusterIP
  selector:
    app: expensepilot-backend-typo-label
  ports:
    - port: 8080
      targetPort: 8080
